### ISSUE TITLE
Update from newer version on SF.net?

### ISSUE THREAD

**Issue by xaratustrah** [petebachant/pyTDMS#1]
Thanks for providing the fork on GitHUB + PyPI of PyTDMS. The only problem is that the GitHUB version crashes on my computer whereas the original code by author on SF.net works very well with the same conditions (Python 3.4, OSX). I only noticed that the last update on SF.net is 6 months newer than your initial commit and few lines are different. Would it be possible to update the GitHUB fork and also the PyPI packge? Thanks!

**Comment by petebachant** [comment]
Sorry I missed this. I will patch and increment the version shortly.
